import type { World } from '../ecs/world';
import { loadGLTF } from './modelLoader';
import { ModelObject } from './modelObject';
import { MonsterObject } from './monsterObject';
import npcModels from './npcModels.json';

type NpcModel = {
  name: string;
  model: string;
  scale: number;
  kind: 'monster' | 'npc';
};

const models = npcModels as Record<string, NpcModel>;
const cache = new Map<number, typeof ModelObject>();

export function getNpcModelInfo(type: number): NpcModel | undefined {
  return models[type];
}

// Model class for a monster/NPC type without a hand written class, built
// from npcModels.json (generated by tools/extractNpcModels.ts).
export function getGenericModelFactory(
  type: number
): typeof ModelObject | undefined {
  const cached = cache.get(type);
  if (cached) return cached;

  const info = models[type];
  // player based NPCs need their equipment set up by a PlayerObject
  if (!info || info.model.startsWith('Player/')) return undefined;

  const Base = info.kind === 'monster' ? MonsterObject : ModelObject;
  const factory = class extends Base {
    async init(world: World) {
      this.load(await loadGLTF(info.model, world));
    }
  };
  factory.OverrideScale = info.scale;

  cache.set(type, factory);
  return factory;
}
