import type { World } from '../ecs/world';
import { loadGLTF } from './modelLoader';
import { ModelObject } from './modelObject';
import { MonsterObject } from './monsterObject';
import { PlayerObject } from './playerObject';
import npcModels from './npcModels.json';
import { modelTypeOf } from './monsterModelAliases';

export { modelTypeOf };

type NpcModel = {
  name: string;
  model: string;
  scale: number;
  kind: 'monster' | 'npc';
  // the model is only a skeleton: body part models (head, upper, lower,
  // gloves, boots) of a numbered variant are added on it
  bodyParts?: { parts: string[]; index: number };
};

const models = npcModels as Record<string, NpcModel>;
const cache = new Map<number, typeof ModelObject>();

const monster = (name: string, model: string, scale = 1): NpcModel => ({
  name,
  model: `Monster/${model}.glb`,
  scale,
  kind: 'monster',
});

// Monsters missing in npcModels.json, with a model chosen by the textures of
// the models ("cundun", "buser", "king"...); their stronger copies use
// the same model (monsterModelAliases.ts).
const EXTRA_MODELS: Record<number, NpcModel> = {
  // Blood Castle 5 monsters without a model
  145: monster('Death Centurion', 'monster68'),
  148: monster('Lord Centurion', 'monster68', 1.1),
  161: monster('Illusion of Kundun', 'monster65'),
  // Devil Square 3-4
  65: monster('Elite Orc', 'Monster48', 1.1),
  66: monster('Cursed King', 'Monster49', 1.1),
  67: monster('Metal Balrog', 'Monster28', 1.6),
  // Devil Square 5-7
  435: monster('Berserk', 'Monster107', 1.1),
};

export function getNpcModelInfo(type: number): NpcModel | undefined {
  const base = modelTypeOf(type);
  return EXTRA_MODELS[base] ?? models[base];
}

// Model class for a monster/NPC type without a hand written class, built
// from npcModels.json (generated by tools/extractNpcModels.ts).
export function getGenericModelFactory(
  type: number
): typeof ModelObject | undefined {
  const cached = cache.get(type);
  if (cached) return cached;

  const info = getNpcModelInfo(type);
  // player based NPCs need their equipment set up by a PlayerObject
  if (!info || info.model.startsWith('Player/')) return undefined;

  const factory = info.bodyParts
    ? createBodyPartsFactory(info.model, info.bodyParts)
    : createSimpleFactory(info);
  factory.OverrideScale = info.scale;

  cache.set(type, factory);
  return factory;
}

function createSimpleFactory(info: NpcModel): typeof ModelObject {
  const Base = info.kind === 'monster' ? MonsterObject : ModelObject;
  return class extends Base {
    async init(world: World) {
      this.load(await loadGLTF(info.model, world));
    }
  };
}

function createBodyPartsFactory(
  model: string,
  { parts, index }: NonNullable<NpcModel['bodyParts']>
): typeof ModelObject {
  const [head, upper, lower, gloves, boots] = parts;
  return class extends PlayerObject {
    async init(world: World) {
      this.load(await loadGLTF(model, world));
      this.setBodyPartsAsync('NPC/', head, upper, lower, gloves, boots, index);
    }
  };
}
