// Names of the NPCs of the later seasons that the monster list of the
// client doesn't have (designations of OpenMU)
export const NPC_NAMES: Record<number, string> = {
  376: 'Pamela the Supplier',
  377: 'Angela the Supplier',
  379: 'Fireworks Girl',
  406: 'Priest Devin',
  407: 'Werewolf Quarrel',
  408: 'Gatekeeper',
  415: 'Silvia',
  417: 'Marce',
  450: 'Cherry Blossom Spirit',
  451: 'Cherry Blossom Tree',
  452: 'Seed Master',
  453: 'Seed Researcher',
  467: 'Snowman',
  468: 'Little Santa Yellow',
  469: 'Little Santa Green',
  470: 'Little Santa Red',
  471: 'Little Santa Blue',
  472: 'Little Santa White',
  473: 'Little Santa Black',
  474: 'Little Santa Orange',
  475: 'Little Santa Pink',
  478: 'Delgado - Lucky Coins',
  479: 'Gatekeeper Titus',
  492: 'Moss The Merchant',
  522: 'Adviser Jerinteu',
  545: 'Christine the General Goods Merchant',
  546: 'Jeweler Raul',
  547: 'Market Union Member Julia',
  577: 'Leina the General Goods Merchant',
  578: 'Weapons Merchant Bolo',
  579: 'David',
};
